### ISSUE TITLE
[ BUG ] - How to cat non-existing profiles or locals.

### ISSUE THREAD

**Issue by UsairimIsani** [rusty-snake/fjp#22]
#  How to cat non-existing profiles or locals.
What should be done if a profile doesn't exist.

Should we prompt the user, the profile you are trying to see doesn't exist, try creating it?

![image](https://user-images.githubusercontent.com/8106387/93592494-b515bf00-f9cb-11ea-95b1-a406c0b7706f.png)

@rusty-snake

**Comment by rusty-snake** [comment]
```
$ fjp cat none
[ERROR fjp::cat] Can not find none.profile.
```

> Should we prompt the user, the profile you are trying to see doesn't exist, try creating it?

On a view function? No.

> How to cat locals.

`fjp cat firefox.local`
