### ISSUE TITLE
Question - Utils

### ISSUE THREAD

**Issue by UsairimIsani** [rusty-snake/fjp#5]
There is a function named "get_name1", is there a significance for the "1" in the functions name?

**Comment by rusty-snake** [comment]
When I wrote this, it was already clear that this will not be the final implementation for a function which expands the profile names. So I added a "1" to the first implementation.

BTW: `profile_path!`, `find_profile` and `get_name1` are soft-deprecated in favour of the code in profile.rs.

**Comment by UsairimIsani** [comment]
Okay Noted. I speculated it was temporary. Can I help with proper migration from these functions?

**Comment by rusty-snake** [comment]
Yes, I already migrated enable/disable (https://github.com/rusty-snake/fjp/commit/b348a9af614626b6039f91f784f46d9e0d9778e1).
