### ISSUE TITLE
Community Discussion forum

### ISSUE THREAD

**Issue by UsairimIsani** [rusty-snake/fjp#9]
Can we have a Discord or Slack or whatever medium you prefer to discuss issues and general questions.

**Comment by rusty-snake** [comment]
Sorry for the delay. I don't use slack, discord... . What advantages would it have over githubs issues?

PS: I hope github will release github discussions soon for all users.

**Comment by UsairimIsani** [comment]
Many Rust based projects have communities around them, usually on Discord. This allows for better interaction between people using these projects and people making these project. 
These communities are not as Formal as GitHub issues are. They are more informal. 
You can understand what people like about your project, what they would like to see etc at a much lighter note.
There are a lot people who use these communities to ask question and interact with users using the project.

Examples
[Rust Language](https://discord.gg/svWQge)
[Tokio](https://discord.gg/cvNjzP)

There are a lot more.

**Comment by rusty-snake** [comment]
https://github.com/rusty-snake/fjp/discussions :rocket: :rocket: :rocket:
